linters:
  disable-all: true
  enable:
    - lll
    - revive
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  lll:
    line-length: 140
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

issues:
  include:
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - typecheck
