name: CI

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Verify dependencies
        run: go mod verify

      - name: Go vet
        run: go vet ./...

      - name: Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: Golint
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

      - name: Security Scanner
        uses: securego/gosec@master
        with:
          args: '-no-fail -fmt sarif -out results.sarif ./...'

  build:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build
        run: go build -v ./...


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Test:unit
        run: |
          go test -v ./... -coverprofile coverage_unit.out -covermode count -tags=unit

      - name: Test:bubbletea
        run: |
          go test -v ./... -coverprofile coverage_bubbletea.out -covermode count -tags=bubbletea

      - name: Coverage
        run: |
          go install github.com/wadey/gocovmerge@latest
          $HOME/go/bin/gocovmerge coverage_unit.out coverage_bubbletea.out > coverage_combined.out
          go tool cover -func coverage_combined.out
