name: CI

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Verify dependencies
        run: go mod verify

      - name: Go vet
        run: go vet ./...

      - name: Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          args: --issues-exit-code=0

  build:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Test:unit
        run: |
          go test -v ./... -coverprofile coverage_unit.out -covermode count -tags=unit

      - name: Test:e2e
        run: |
          go test -v ./... -coverprofile coverage_e2e.out -covermode count -tags=e2e

      - name: Coverage
        run: |
          go install github.com/wadey/gocovmerge@latest
          $HOME/go/bin/gocovmerge coverage_unit.out coverage_e2e.out > coverage_combined.out
          go tool cover -func coverage_combined.out

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
