name: CI

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Verify dependencies
        run: go mod verify

      - name: Go vet
        run: go vet ./...

      - name: Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: Golint
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Go modules
        uses: actions/cache@v2
        id: cache-go-modules
        with:
          path: ${{ env.GOPATH }}/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Reuse cached Go modules
        uses: actions/cache@v2
        with:
          path: ${{ env.GOPATH }}/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Test:unit
        run: |
          go test -v ./... -coverprofile coverage_unit.out -covermode count -tags=unit

      - name: Test:bubbletea
        run: |
          go test -v ./... -coverprofile coverage_bubbletea.out -covermode count -tags=bubbletea

      - name: Coverage
        run: |
          go install github.com/wadey/gocovmerge@latest
          $HOME/go/bin/gocovmerge coverage_unit.out coverage_bubbletea.out > coverage_combined.out
          go tool cover -func coverage_combined.out
